### ISSUE TITLE
Playing local audio files

### ISSUE THREAD

**Issue by jasecoop** [jhabdas/lumpen-radio#3]
Hi @jhabdas

Thanks for making this open source! I've been following your comments over in react-native-video and it's been really useful.

I was wondering if you'd be able to help me, how would I pay a local file to AudioManager? Rather than stream from a URL. Is this possible?

Thanks

**Comment by jhabdas** [comment]
@jasecoop You're welcome. In addition to the information on Brent's module you may also find my [Build a streaming audio app with React Native talks](http://habd.as/about/#talks) helpful. One is just the slide deck and the other is a video web cast to those slides.

The Pod I'm using called `StreamingKit` (`STK` namespace in the iOS source files) [supports playback](https://github.com/tumtumtum/StreamingKit/#main-features) of local resources. Add the resources to your project in Xcode and link them to the binary in Build Settings there as well. You should then be able to access them in React land. If you land on a good pattern I'd love to see even a Gist of how you got it working so we can look at later abstracting a generalized sound library.

Also, if you struggle with background audio I've documented how to do it thoroughly here:
https://github.com/tumtumtum/StreamingKit/wiki/Background-Audio

Good luck!

**Comment by jasecoop** [comment]
@jhabdas Thank you for the quick reply!

Struggling to find some good examples, but my objective C sucks (designer getting to grips with react-native).

Currently trying this but having no luck, any ideas why this might be throwing this error?

![image](https://cloud.githubusercontent.com/assets/588780/12862259/ce92e550-cc1e-11e5-9911-4626f4dedb01.png)


```
RCT_EXPORT_METHOD(play)
{
  if (!self.audioPlayer) {
    return;
  }
  if (self.audioPlayer.state == STKAudioPlayerStatePaused) {
    [self.audioPlayer resume];
  } else {
    // [self.audioPlayer play:LPN_AUDIO_STREAM_URL];
    NSString* path = [[NSBundle mainBundle] pathForResource:@"testFile" ofType:@"mp3"];
    NSURL* url = [NSURL fileURLWithPath:path];
    STKDataSource* dataSource = [STKAudioPlayer dataSourceFromURL:url];
    [self.audioPlayer play:url];
    // [audioPlayer play:dataSource withQueueItemId:[[SampleQueueId alloc] initWithUrl:url andCount:0]];
  }
}
```
