### ISSUE TITLE
"STKDataSource.h" file not found

### ISSUE THREAD

**Issue by mikeurnun** [jhabdas/lumpen-radio#4]
Hi @jhabdas,

Thanks for sharing & making this open source! I'm trying to build my first iOS app using your code since i come from javascript background. My build keeps failing with "STKDataSource.h file not found" error in STKAudioPlayer.h file. I've followed exact steps in the instruction when installing and I get all green after i run `npm start` and am targeting iOS 9.2 deployment in WLPN.xcworkspace.

I've ran `pod install` religiously and I'm aware that there was a similar issue raised here previously and you've already merged the confirmed fix but there seems to be something specific to the way i install or in the env that's recreating this issue.

Any advise/suggestions are greatly appreciated!

**Comment by mikeurnun** [comment]
q11qq1

**Comment by jhabdas** [comment]
Hi @mikeurnun. I believe I saw this during development. IIRC you'll need to ensure you are not receiving any Pod errors during installation. It can be a little tricky to get past the first time.

If you're setting up a new project, I'd recommend starting from a seed project like the [`react-native-webpack-starter-kit`](https://github.com/jhabdas/react-native-webpack-starter-kit) I extracted from this project following development. The `README` there also links to a reference page on my blog containing a number of other RN app seeds. Please try and avoid anything which does too much while getting started as they will tend to go out-of-date the soonest and pose the most difficulty in maintaining an effective and efficient development environment.

**Comment by gustavovnicius** [comment]
I've solved this by removing the versioned `Pods` dir on the root of lumpen and executing `pod install` again.

**Comment by jhabdas** [comment]
Glad to hear you were able to make progress. This app has a hard dependency on the STK pod, but that can be changed with a little elbow grease. Good luck and have fun out there!

**Comment by mikeurnun** [comment]
@gustavovnicius - that works for me too! Thanks guys!
