### ISSUE TITLE
Doesn't work for Android

### ISSUE THREAD

**Issue by danielbair** [jhabdas/lumpen-radio#6]
After wasting many hours it is clear that the Android app is nothing more than a "Welcome to React Native" skeleton.

Will there be an android app in the near future?

**Comment by jhabdas** [comment]
Hi @danielbair. Sorry to hear you lost time. This app was built before RN supported Android and I don't have plans personally to build out an Android version. Would accept PRs though, after the kit is updated to the latest version of https://github.com/jhabdas/react-native-webpack-starter-kit.
